export interface College {
  id: string;
  name: string;
  slug: string;
  type: "Government" | "Private" | "Deemed" | "Autonomous";
  established: number;
  description: string;
  logo: string;
  banner: string;
  country: string;
  state: string;
  city: string;
  courses: Course[];
  rankingNirf: number | null;
  avgPackageLpa: number;
  highestPackageLpa: number;
  placementPercentage: number;
  totalStudents: number;
  facilities: string[];
  avgRating: number;
  totalReviews: number;
  feeRange: string;
  website: string;
}

export interface Course {
  name: string;
  degreeLevel: string;
  duration: string;
  feePerYear: number;
  eligibility: string;
}

export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  category: string;
  coverImage: string;
  author: string;
  publishedAt: string;
  readTime: string;
}

export interface Scholarship {
  id: string;
  name: string;
  provider: string;
  amount: string;
  deadline: string;
  eligibility: string;
  countries: string[];
}

export interface ExamInfo {
  id: string;
  name: string;
  fullName: string;
  category: string;
  examDate: string;
  registrationDeadline: string;
  description: string;
}

export const colleges: College[] = [
  {
    id: "1",
    name: "Indian Institute of Technology, Bombay",
    slug: "iit-bombay",
    type: "Government",
    established: 1958,
    description: "IIT Bombay is one of India's premier engineering institutions, known for its cutting-edge research, world-class faculty, and exceptional placement records. Located in Powai, Mumbai, it offers a vibrant campus life with state-of-the-art facilities.",
    logo: "https://ui-avatars.com/api/?name=IIT+B&background=1e40af&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    courses: [
      { name: "B.Tech Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 225000, eligibility: "JEE Advanced Rank < 500" },
      { name: "B.Tech Electrical Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 225000, eligibility: "JEE Advanced Rank < 1000" },
      { name: "M.Tech AI & Data Science", degreeLevel: "PG", duration: "2 Years", feePerYear: 100000, eligibility: "GATE Score > 750" },
    ],
    rankingNirf: 3,
    avgPackageLpa: 21.0,
    highestPackageLpa: 280.0,
    placementPercentage: 95,
    totalStudents: 11000,
    facilities: ["Hostel", "Library", "Sports Complex", "WiFi", "Labs", "Gym", "Swimming Pool"],
    avgRating: 4.7,
    totalReviews: 342,
    feeRange: "2-2.5L/year",
    website: "https://www.iitb.ac.in",
  },
  {
    id: "2",
    name: "Indian Institute of Technology, Delhi",
    slug: "iit-delhi",
    type: "Government",
    established: 1961,
    description: "IIT Delhi is a world-renowned institution for engineering and technology education. Situated in the heart of New Delhi, it provides excellent academic programs and research opportunities.",
    logo: "https://ui-avatars.com/api/?name=IIT+D&background=7c3aed&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    country: "India",
    state: "Delhi",
    city: "New Delhi",
    courses: [
      { name: "B.Tech Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 210000, eligibility: "JEE Advanced Rank < 300" },
      { name: "B.Tech Mechanical Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 210000, eligibility: "JEE Advanced Rank < 1500" },
      { name: "MBA", degreeLevel: "PG", duration: "2 Years", feePerYear: 1200000, eligibility: "CAT Score > 98 percentile" },
    ],
    rankingNirf: 2,
    avgPackageLpa: 23.5,
    highestPackageLpa: 310.0,
    placementPercentage: 96,
    totalStudents: 9500,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports Complex", "Research Park"],
    avgRating: 4.8,
    totalReviews: 412,
    feeRange: "2.1-12L/year",
    website: "https://www.iitd.ac.in",
  },
  {
    id: "3",
    name: "National Institute of Technology, Trichy",
    slug: "nit-trichy",
    type: "Government",
    established: 1964,
    description: "NIT Trichy is one of the top NITs in India, known for strong academic programs in engineering, architecture, and management. Located in Tamil Nadu, it has a sprawling green campus.",
    logo: "https://ui-avatars.com/api/?name=NIT+T&background=059669&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    country: "India",
    state: "Tamil Nadu",
    city: "Tiruchirappalli",
    courses: [
      { name: "B.Tech Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 150000, eligibility: "JEE Main Rank < 5000" },
      { name: "B.Tech Electronics", degreeLevel: "UG", duration: "4 Years", feePerYear: 150000, eligibility: "JEE Main Rank < 8000" },
    ],
    rankingNirf: 9,
    avgPackageLpa: 12.5,
    highestPackageLpa: 65.0,
    placementPercentage: 92,
    totalStudents: 7500,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Canteen", "Sports"],
    avgRating: 4.3,
    totalReviews: 189,
    feeRange: "1.5L/year",
    website: "https://www.nitt.edu",
  },
  {
    id: "4",
    name: "Massachusetts Institute of Technology",
    slug: "mit",
    type: "Private",
    established: 1861,
    description: "MIT is a world-leading university for science, technology, and engineering, located in Cambridge, Massachusetts. It consistently ranks among the top universities globally.",
    logo: "https://ui-avatars.com/api/?name=MIT&background=dc2626&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
    country: "USA",
    state: "Massachusetts",
    city: "Cambridge",
    courses: [
      { name: "BS Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 5700000, eligibility: "SAT > 1550, Strong extracurriculars" },
      { name: "MS Artificial Intelligence", degreeLevel: "PG", duration: "2 Years", feePerYear: 5700000, eligibility: "GRE > 330, Research experience" },
    ],
    rankingNirf: null,
    avgPackageLpa: 150.0,
    highestPackageLpa: 500.0,
    placementPercentage: 98,
    totalStudents: 11500,
    facilities: ["Housing", "Library", "Research Labs", "WiFi", "Gym", "Innovation Hub"],
    avgRating: 4.9,
    totalReviews: 156,
    feeRange: "57L/year",
    website: "https://www.mit.edu",
  },
  {
    id: "5",
    name: "University of Oxford",
    slug: "oxford",
    type: "Government",
    established: 1096,
    description: "The University of Oxford is the oldest university in the English-speaking world, renowned for its tutorial system, ancient colleges, and world-class research output.",
    logo: "https://ui-avatars.com/api/?name=OX&background=1e3a5f&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    country: "UK",
    state: "Oxfordshire",
    city: "Oxford",
    courses: [
      { name: "BA Computer Science", degreeLevel: "UG", duration: "3 Years", feePerYear: 3800000, eligibility: "A-Levels AAA, IELTS 7.5+" },
      { name: "MSc Data Science", degreeLevel: "PG", duration: "1 Year", feePerYear: 4200000, eligibility: "First-class degree, GRE recommended" },
    ],
    rankingNirf: null,
    avgPackageLpa: 120.0,
    highestPackageLpa: 400.0,
    placementPercentage: 95,
    totalStudents: 24000,
    facilities: ["Historic Colleges", "Bodleian Library", "Labs", "WiFi", "Sports", "Museums"],
    avgRating: 4.8,
    totalReviews: 203,
    feeRange: "38-42L/year",
    website: "https://www.ox.ac.uk",
  },
  {
    id: "6",
    name: "Vellore Institute of Technology",
    slug: "vit-vellore",
    type: "Private",
    established: 1984,
    description: "VIT is one of India's top private engineering universities, located in Vellore, Tamil Nadu. Known for its own entrance exam VITEEE and strong industry connections.",
    logo: "https://ui-avatars.com/api/?name=VIT&background=f59e0b&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    country: "India",
    state: "Tamil Nadu",
    city: "Vellore",
    courses: [
      { name: "B.Tech Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 350000, eligibility: "VITEEE or JEE Main" },
      { name: "B.Tech AI & ML", degreeLevel: "UG", duration: "4 Years", feePerYear: 400000, eligibility: "VITEEE or JEE Main" },
    ],
    rankingNirf: 12,
    avgPackageLpa: 8.5,
    highestPackageLpa: 44.0,
    placementPercentage: 88,
    totalStudents: 35000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Gym", "Canteen"],
    avgRating: 4.1,
    totalReviews: 567,
    feeRange: "3.5-4L/year",
    website: "https://www.vit.ac.in",
  },
  {
    id: "7",
    name: "University of Toronto",
    slug: "u-toronto",
    type: "Government",
    established: 1827,
    description: "The University of Toronto is Canada's top-ranked university, known for groundbreaking research in AI, medicine, and engineering. Located in downtown Toronto.",
    logo: "https://ui-avatars.com/api/?name=UT&background=2563eb&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    courses: [
      { name: "BASc Computer Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 4500000, eligibility: "90%+ average, IELTS 7+" },
      { name: "MSc Computer Science", degreeLevel: "PG", duration: "2 Years", feePerYear: 3200000, eligibility: "B+ average, GRE recommended" },
    ],
    rankingNirf: null,
    avgPackageLpa: 90.0,
    highestPackageLpa: 350.0,
    placementPercentage: 93,
    totalStudents: 97000,
    facilities: ["Housing", "Libraries", "Research Labs", "WiFi", "Gym", "Career Center"],
    avgRating: 4.6,
    totalReviews: 178,
    feeRange: "32-45L/year",
    website: "https://www.utoronto.ca",
  },
  {
    id: "8",
    name: "BITS Pilani",
    slug: "bits-pilani",
    type: "Deemed",
    established: 1964,
    description: "BITS Pilani is a leading deemed university with campuses in Pilani, Goa, and Hyderabad. Known for its flexible academic structure and strong industry practice program.",
    logo: "https://ui-avatars.com/api/?name=BITS&background=be185d&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    country: "India",
    state: "Rajasthan",
    city: "Pilani",
    courses: [
      { name: "B.E. Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 500000, eligibility: "BITSAT Score > 350" },
      { name: "B.E. Electronics", degreeLevel: "UG", duration: "4 Years", feePerYear: 500000, eligibility: "BITSAT Score > 300" },
      { name: "M.E. Software Systems", degreeLevel: "PG", duration: "2 Years", feePerYear: 300000, eligibility: "BITS degree or GATE" },
    ],
    rankingNirf: 16,
    avgPackageLpa: 16.0,
    highestPackageLpa: 90.0,
    placementPercentage: 90,
    totalStudents: 15000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Entrepreneurship Cell"],
    avgRating: 4.5,
    totalReviews: 298,
    feeRange: "5L/year",
    website: "https://www.bits-pilani.ac.in",
  },
  {
    id: "9",
    name: "Indian Institute of Science (IISc)",
    slug: "iisc-bangalore",
    type: "Government",
    established: 1909,
    description: "IISc Bangalore is India's premier research institution, consistently ranked #1 by NIRF for research. Founded by Jamsetji Tata, it offers world-class programs in science, engineering, and design with a beautiful 400-acre campus in the heart of Bangalore.",
    logo: "https://ui-avatars.com/api/?name=IISc&background=1e3a5f&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "BS (Research) in Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 50000, eligibility: "JEE Advanced / KVPY / NEET top rankers" },
      { name: "M.Tech Computer Science", degreeLevel: "PG", duration: "2 Years", feePerYear: 35000, eligibility: "GATE Score > 800" },
      { name: "PhD in AI & ML", degreeLevel: "PhD", duration: "5 Years", feePerYear: 35000, eligibility: "M.Tech/ME with GATE or IISc entrance" },
    ],
    rankingNirf: 1,
    avgPackageLpa: 35.0,
    highestPackageLpa: 150.0,
    placementPercentage: 85,
    totalStudents: 4500,
    facilities: ["Hostel", "Library", "Research Labs", "WiFi", "Gym", "Sports Complex", "Supercomputer Center"],
    avgRating: 4.9,
    totalReviews: 210,
    feeRange: "0.35-0.5L/year",
    website: "https://www.iisc.ac.in",
  },
  {
    id: "10",
    name: "RV College of Engineering",
    slug: "rvce-bangalore",
    type: "Private",
    established: 1963,
    description: "RVCE is one of Bangalore's oldest and most prestigious engineering colleges, affiliated to VTU. Located in Mysore Road, it's known for strong placements, active coding culture, and excellent infrastructure.",
    logo: "https://ui-avatars.com/api/?name=RVCE&background=4f46e5&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.E. Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 295000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Electronics & Communication", degreeLevel: "UG", duration: "4 Years", feePerYear: 280000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Information Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 290000, eligibility: "KCET / COMEDK Rank" },
      { name: "M.Tech VLSI Design", degreeLevel: "PG", duration: "2 Years", feePerYear: 150000, eligibility: "GATE qualified" },
    ],
    rankingNirf: 68,
    avgPackageLpa: 12.0,
    highestPackageLpa: 60.0,
    placementPercentage: 92,
    totalStudents: 5000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Canteen", "Auditorium"],
    avgRating: 4.3,
    totalReviews: 423,
    feeRange: "2.8-3L/year",
    website: "https://www.rvce.edu.in",
  },
  {
    id: "11",
    name: "PES University",
    slug: "pes-university-bangalore",
    type: "Private",
    established: 1972,
    description: "PES University is a top private university in Bangalore known for its B.Tech programs, especially in Computer Science and Electronics. The Ring Road campus offers modern facilities and a strong startup ecosystem.",
    logo: "https://ui-avatars.com/api/?name=PES&background=dc2626&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.Tech Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 450000, eligibility: "PESSAT / KCET / COMEDK" },
      { name: "B.Tech Electronics & Communication", degreeLevel: "UG", duration: "4 Years", feePerYear: 400000, eligibility: "PESSAT / KCET / COMEDK" },
      { name: "B.Tech AI & ML", degreeLevel: "UG", duration: "4 Years", feePerYear: 475000, eligibility: "PESSAT / KCET / COMEDK" },
      { name: "MBA", degreeLevel: "PG", duration: "2 Years", feePerYear: 500000, eligibility: "CAT / PGCET / MAT" },
    ],
    rankingNirf: 72,
    avgPackageLpa: 10.5,
    highestPackageLpa: 50.0,
    placementPercentage: 89,
    totalStudents: 12000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Innovation Center", "Gym"],
    avgRating: 4.2,
    totalReviews: 567,
    feeRange: "4-4.75L/year",
    website: "https://www.pes.edu",
  },
  {
    id: "12",
    name: "BMS College of Engineering",
    slug: "bmsce-bangalore",
    type: "Private",
    established: 1946,
    description: "BMSCE is one of India's oldest private engineering colleges, located in Bull Temple Road, Bangalore. Known for its strong alumni network, excellent placements, and heritage campus with modern labs.",
    logo: "https://ui-avatars.com/api/?name=BMS&background=0891b2&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.E. Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 260000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Mechanical Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 240000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Information Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 260000, eligibility: "KCET / COMEDK Rank" },
    ],
    rankingNirf: 81,
    avgPackageLpa: 9.5,
    highestPackageLpa: 44.0,
    placementPercentage: 90,
    totalStudents: 4500,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Canteen", "Workshop"],
    avgRating: 4.2,
    totalReviews: 389,
    feeRange: "2.4-2.6L/year",
    website: "https://www.bmsce.ac.in",
  },
  {
    id: "13",
    name: "MS Ramaiah Institute of Technology",
    slug: "msrit-bangalore",
    type: "Private",
    established: 1962,
    description: "MSRIT is a premier engineering college in Bangalore affiliated to VTU. Located in MSR Nagar, Mathikere, it offers excellent infrastructure, strong industry connections, and consistent placement records.",
    logo: "https://ui-avatars.com/api/?name=MSRIT&background=9333ea&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.E. Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 280000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Electronics & Communication", degreeLevel: "UG", duration: "4 Years", feePerYear: 270000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Information Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 280000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Mechanical Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 250000, eligibility: "KCET / COMEDK Rank" },
    ],
    rankingNirf: 89,
    avgPackageLpa: 9.0,
    highestPackageLpa: 42.0,
    placementPercentage: 88,
    totalStudents: 6000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Canteen", "Incubation Center"],
    avgRating: 4.1,
    totalReviews: 456,
    feeRange: "2.5-2.8L/year",
    website: "https://www.msrit.edu",
  },
  {
    id: "14",
    name: "Christ University",
    slug: "christ-university-bangalore",
    type: "Deemed",
    established: 1969,
    description: "Christ University is a prestigious deemed university in Bangalore, known for its strong BBA, BCom, and liberal arts programs. Located in Hosur Road, it emphasizes holistic education, discipline, and all-round development.",
    logo: "https://ui-avatars.com/api/?name=CU&background=059669&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "BBA", degreeLevel: "UG", duration: "3 Years", feePerYear: 300000, eligibility: "Christ University Entrance Test" },
      { name: "BCom (Honours)", degreeLevel: "UG", duration: "3 Years", feePerYear: 200000, eligibility: "Christ University Entrance Test" },
      { name: "B.Tech Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 350000, eligibility: "KCET / CUET / Christ Entrance" },
      { name: "MBA", degreeLevel: "PG", duration: "2 Years", feePerYear: 500000, eligibility: "CAT / MAT / Christ Entrance" },
      { name: "MA Psychology", degreeLevel: "PG", duration: "2 Years", feePerYear: 150000, eligibility: "Christ University Entrance Test" },
    ],
    rankingNirf: 30,
    avgPackageLpa: 7.0,
    highestPackageLpa: 28.0,
    placementPercentage: 85,
    totalStudents: 28000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Auditorium", "Gym", "Canteen"],
    avgRating: 4.3,
    totalReviews: 780,
    feeRange: "2-5L/year",
    website: "https://www.christuniversity.in",
  },
  {
    id: "15",
    name: "Bangalore Institute of Technology",
    slug: "bit-bangalore",
    type: "Private",
    established: 1979,
    description: "BIT Bangalore is a well-established engineering college affiliated to VTU, located in KR Road. Known for affordable education with decent placements and a strong alumni network in the Bangalore tech industry.",
    logo: "https://ui-avatars.com/api/?name=BIT&background=ea580c&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.E. Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 180000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Electronics & Communication", degreeLevel: "UG", duration: "4 Years", feePerYear: 170000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Civil Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 150000, eligibility: "KCET / COMEDK Rank" },
    ],
    rankingNirf: null,
    avgPackageLpa: 6.5,
    highestPackageLpa: 25.0,
    placementPercentage: 82,
    totalStudents: 3500,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Canteen"],
    avgRating: 3.9,
    totalReviews: 234,
    feeRange: "1.5-1.8L/year",
    website: "https://www.bit-bangalore.edu.in",
  },
  {
    id: "16",
    name: "Nitte Meenakshi Institute of Technology",
    slug: "nmit-bangalore",
    type: "Private",
    established: 2001,
    description: "NMIT is a well-known engineering college in Yelahanka, Bangalore, affiliated to VTU. It offers quality engineering education with a modern campus, good industry connections, and growing placement records.",
    logo: "https://ui-avatars.com/api/?name=NMIT&background=7c3aed&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.E. Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 250000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. AI & ML", degreeLevel: "UG", duration: "4 Years", feePerYear: 275000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Electronics & Communication", degreeLevel: "UG", duration: "4 Years", feePerYear: 240000, eligibility: "KCET / COMEDK Rank" },
    ],
    rankingNirf: null,
    avgPackageLpa: 7.0,
    highestPackageLpa: 30.0,
    placementPercentage: 85,
    totalStudents: 4000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Canteen", "Gym"],
    avgRating: 4.0,
    totalReviews: 312,
    feeRange: "2.4-2.75L/year",
    website: "https://www.nmit.ac.in",
  },
  {
    id: "17",
    name: "International Institute of Information Technology, Bangalore",
    slug: "iiitb-bangalore",
    type: "Deemed",
    established: 1999,
    description: "IIIT-B is an elite institution focused on IT and computing, located in Electronic City, Bangalore. Known for its integrated M.Tech program, research output, and exceptional placements in top tech companies.",
    logo: "https://ui-avatars.com/api/?name=IIITB&background=1e40af&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "Integrated M.Tech (CSE)", degreeLevel: "PG", duration: "2 Years", feePerYear: 750000, eligibility: "GATE Score > 600 or IIIT-B entrance" },
      { name: "M.Tech Digital Society", degreeLevel: "PG", duration: "2 Years", feePerYear: 700000, eligibility: "GATE qualified" },
      { name: "PhD in Computer Science", degreeLevel: "PhD", duration: "4-5 Years", feePerYear: 100000, eligibility: "M.Tech with strong research background" },
    ],
    rankingNirf: 55,
    avgPackageLpa: 22.0,
    highestPackageLpa: 75.0,
    placementPercentage: 95,
    totalStudents: 1500,
    facilities: ["Hostel", "Library", "Research Labs", "WiFi", "Gym", "Innovation Hub"],
    avgRating: 4.6,
    totalReviews: 178,
    feeRange: "7-7.5L/year",
    website: "https://www.iiitb.ac.in",
  },
  {
    id: "18",
    name: "Jain University",
    slug: "jain-university-bangalore",
    type: "Deemed",
    established: 1990,
    description: "Jain University is a multidisciplinary deemed university in Bangalore offering programs across engineering, management, sciences, humanities, and commerce. Known for its modern campuses and industry-integrated curriculum.",
    logo: "https://ui-avatars.com/api/?name=JU&background=ca8a04&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.Tech Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 300000, eligibility: "JET / KCET / COMEDK" },
      { name: "BBA", degreeLevel: "UG", duration: "3 Years", feePerYear: 250000, eligibility: "Jain Entrance Test" },
      { name: "B.Sc Animation & VFX", degreeLevel: "UG", duration: "3 Years", feePerYear: 350000, eligibility: "Jain Entrance Test" },
      { name: "MBA", degreeLevel: "PG", duration: "2 Years", feePerYear: 450000, eligibility: "CAT / MAT / Jain Entrance" },
    ],
    rankingNirf: 85,
    avgPackageLpa: 6.0,
    highestPackageLpa: 22.0,
    placementPercentage: 80,
    totalStudents: 20000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Gym", "Auditorium", "Canteen"],
    avgRating: 4.0,
    totalReviews: 645,
    feeRange: "2.5-4.5L/year",
    website: "https://www.jainuniversity.ac.in",
  },
  {
    id: "19",
    name: "SEA College of Engineering & Technology",
    slug: "sea-college-bangalore",
    type: "Private",
    established: 2000,
    description: "SEA College of Engineering & Technology is part of the South East Asian Education Trust with 25 years of excellence in education. Located in KR Puram, Bangalore, the campus hosts 12 institutions including engineering, management, law, nursing, and arts colleges. Known for its diverse international student body with 500+ students from across the globe, modern labs, and strong mentorship programs.",
    logo: "https://ui-avatars.com/api/?name=SEA&background=0d9488&color=fff&size=80",
    banner: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    courses: [
      { name: "B.E. Computer Science", degreeLevel: "UG", duration: "4 Years", feePerYear: 150000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Electronics & Communication", degreeLevel: "UG", duration: "4 Years", feePerYear: 140000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Civil Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 120000, eligibility: "KCET / COMEDK Rank" },
      { name: "B.E. Mechanical Engineering", degreeLevel: "UG", duration: "4 Years", feePerYear: 130000, eligibility: "KCET / COMEDK Rank" },
      { name: "M.Tech (VTU)", degreeLevel: "PG", duration: "2 Years", feePerYear: 100000, eligibility: "GATE qualified / VTU PGCET" },
      { name: "MBA (VTU)", degreeLevel: "PG", duration: "2 Years", feePerYear: 120000, eligibility: "PGCET / KMAT / CAT / MAT" },
      { name: "M.Com", degreeLevel: "PG", duration: "2 Years", feePerYear: 60000, eligibility: "B.Com degree" },
      { name: "BBA", degreeLevel: "UG", duration: "3 Years", feePerYear: 80000, eligibility: "12th pass (any stream)" },
      { name: "BCom", degreeLevel: "UG", duration: "3 Years", feePerYear: 50000, eligibility: "12th pass (Commerce)" },
      { name: "BA LLB (Law)", degreeLevel: "UG", duration: "5 Years", feePerYear: 100000, eligibility: "CLAT / Karnataka KLEE" },
      { name: "B.Sc Nursing", degreeLevel: "UG", duration: "4 Years", feePerYear: 150000, eligibility: "12th with PCB, NEET qualified" },
      { name: "B.Ed", degreeLevel: "UG", duration: "2 Years", feePerYear: 60000, eligibility: "Graduation with 50%" },
    ],
    rankingNirf: null,
    avgPackageLpa: 4.5,
    highestPackageLpa: 12.0,
    placementPercentage: 78,
    totalStudents: 8000,
    facilities: ["Hostel", "Library", "Labs", "WiFi", "Sports", "Canteen", "Gym", "Yoga Center", "Auditorium", "Research Center"],
    avgRating: 3.8,
    totalReviews: 195,
    feeRange: "0.5-1.5L/year",
    website: "https://seaedu.ac.in",
  },
];

export const blogPosts: BlogPost[] = [
  { id: "1", title: "How to Crack JEE Advanced 2026: Complete Strategy Guide", slug: "crack-jee-advanced-2026", excerpt: "A comprehensive guide covering preparation strategy, best books, time management, and last-minute tips for JEE Advanced 2026.", category: "Exam Prep", coverImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80", author: "Dr. Priya Sharma", publishedAt: "2026-03-28", readTime: "8 min" },
  { id: "2", title: "Top 10 Countries for Indian Students to Study Abroad in 2026", slug: "top-countries-study-abroad-2026", excerpt: "Comparing tuition fees, living costs, work opportunities, and visa policies across the best study abroad destinations for Indian students.", category: "Study Abroad", coverImage: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80", author: "Ankit Verma", publishedAt: "2026-03-25", readTime: "6 min" },
  { id: "3", title: "Writing a Winning Statement of Purpose: Tips & Templates", slug: "writing-winning-sop", excerpt: "Step-by-step guide to crafting an SOP that stands out, with real examples from successful applicants to top universities.", category: "Admission Tips", coverImage: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80", author: "Meera Nair", publishedAt: "2026-03-20", readTime: "10 min" },
  { id: "4", title: "Career in AI & Machine Learning: Complete Roadmap 2026", slug: "career-ai-ml-roadmap", excerpt: "From beginner to expert — learn what skills, courses, and certifications you need for a successful career in AI and ML.", category: "Career Advice", coverImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80", author: "Rahul Gupta", publishedAt: "2026-03-15", readTime: "12 min" },
  { id: "5", title: "NEET UG 2026: Important Dates, Syllabus & Preparation Tips", slug: "neet-ug-2026-guide", excerpt: "Everything you need to know about NEET UG 2026 — registration dates, exam pattern, syllabus changes, and effective study strategies.", category: "Exam Prep", coverImage: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&q=80", author: "Dr. Arjun Mehta", publishedAt: "2026-03-10", readTime: "7 min" },
  { id: "6", title: "Scholarships for Indian Students: Complete List 2026-27", slug: "scholarships-indian-students-2026", excerpt: "Comprehensive list of merit-based, need-based, and government scholarships available for Indian students studying in India and abroad.", category: "Scholarships", coverImage: "https://images.unsplash.com/photo-1627556704302-624286467c65?w=800&q=80", author: "Sunita Reddy", publishedAt: "2026-03-05", readTime: "9 min" },
];

export const scholarships: Scholarship[] = [
  { id: "1", name: "INSPIRE Scholarship", provider: "DST, Government of India", amount: "80,000/year", deadline: "2026-10-31", eligibility: "Top 1% in 12th boards", countries: ["India"] },
  { id: "2", name: "Commonwealth Scholarship", provider: "Commonwealth Commission", amount: "Full tuition + living", deadline: "2026-12-15", eligibility: "Indian citizens, PG/PhD applicants", countries: ["UK"] },
  { id: "3", name: "Fulbright-Nehru Fellowship", provider: "USIEF", amount: "Full funding", deadline: "2026-06-15", eligibility: "Indian citizens with 3+ years experience", countries: ["USA"] },
  { id: "4", name: "KVPY Fellowship", provider: "IISc Bangalore", amount: "5,000-7,000/month", deadline: "2026-08-31", eligibility: "Students in class 11/12 or 1st year UG", countries: ["India"] },
  { id: "5", name: "Chevening Scholarship", provider: "UK Government", amount: "Full tuition + living", deadline: "2026-11-01", eligibility: "2+ years work experience, return to home country", countries: ["UK"] },
];

export const exams: ExamInfo[] = [
  { id: "1", name: "JEE Main", fullName: "Joint Entrance Examination Main", category: "Engineering", examDate: "2026-04-10", registrationDeadline: "2026-03-15", description: "National level exam for admission to NITs, IIITs, and other engineering colleges." },
  { id: "2", name: "JEE Advanced", fullName: "Joint Entrance Examination Advanced", category: "Engineering", examDate: "2026-06-01", registrationDeadline: "2026-05-10", description: "Gateway to IITs. Only top 2,50,000 JEE Main qualifiers eligible." },
  { id: "3", name: "NEET UG", fullName: "National Eligibility cum Entrance Test", category: "Medical", examDate: "2026-05-05", registrationDeadline: "2026-03-20", description: "Single entrance exam for admission to MBBS, BDS, and AYUSH courses in India." },
  { id: "4", name: "CAT", fullName: "Common Admission Test", category: "Management", examDate: "2026-11-24", registrationDeadline: "2026-09-15", description: "Premier management entrance test for admission to IIMs and top B-schools." },
  { id: "5", name: "GRE", fullName: "Graduate Record Examination", category: "Abroad", examDate: "Year-round", registrationDeadline: "Flexible", description: "Standardized test for graduate school admissions, primarily in the US and Canada." },
  { id: "6", name: "IELTS", fullName: "International English Language Testing System", category: "Abroad", examDate: "Year-round", registrationDeadline: "Flexible", description: "English language proficiency test accepted by universities worldwide." },
];

export const testimonials = [
  { name: "Priya Menon", role: "IIT Bombay, B.Tech CSE", text: "EduConnect helped me track all my application deadlines in one place. I never missed a single one!", avatar: "PM" },
  { name: "Rohit Sharma", role: "University of Toronto, MSc CS", text: "The study abroad guides were incredibly detailed. I found scholarships I didn't even know existed.", avatar: "RS" },
  { name: "Ananya Gupta", role: "NIT Trichy, B.Tech ECE", text: "The college comparison tool made my decision so much easier. Being able to see fees, placements, and rankings side by side was a game-changer.", avatar: "AG" },
];

export const stats = [
  { label: "Colleges Listed", value: "500+" },
  { label: "Active Students", value: "25,000+" },
  { label: "Countries Covered", value: "15+" },
  { label: "Career Paths", value: "100+" },
];
